<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class PersonenTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('personen')->insert([
            [
                'id' => 1,
                'gezinid' => null,
                'voornaam' => 'Hans',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Leeuwen',
                'geboortedatum' => '1958-02-12',
                'typepersoon' => 'Manager',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 2,
                'gezinid' => null,
                'voornaam' => 'Jan',
                'tussenvoegsel' => 'van der',
                'achternaam' => 'Sluijs',
                'geboortedatum' => '1993-04-30',
                'typepersoon' => 'Medewerker',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 3,
                'gezinid' => null,
                'voornaam' => 'Herman',
                'tussenvoegsel' => 'den',
                'achternaam' => 'Duiker',
                'geboortedatum' => '1989-08-30',
                'typepersoon' => 'Vrijwilliger',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 4,
                'gezinid' => 1,
                'voornaam' => 'Johan',
                'tussenvoegsel' => 'vann',
                'achternaam' => 'Zevenhuizen',
                'geboortedatum' => '1990-05-20',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 1,
            ],
            [
                'id' => 5,
                'gezinid' => 1,
                'voornaam' => 'Sarah',
                'tussenvoegsel' => 'den',
                'achternaam' => 'Dolder',
                'geboortedatum' => '1985-03-23',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 6,
                'gezinid' => 1,
                'voornaam' => 'Theo',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Zevenhuizen',
                'geboortedatum' => '2015-03-08',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 7,
                'gezinid' => 1,
                'voornaam' => 'Jantien',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Zevenhuizen',
                'geboortedatum' => '2016-09-20',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 8,
                'gezinid' => 2,
                'voornaam' => 'Arjan',
                'tussenvoegsel' => null,
                'achternaam' => 'Bergkamp',
                'geboortedatum' => '1968-07-12',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 1,
            ],
            [
                'id' => 9,
                'gezinid' => 2,
                'voornaam' => 'Janneke',
                'tussenvoegsel' => null,
                'achternaam' => 'Sanders',
                'geboortedatum' => '1969-05-11',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 10,
                'gezinid' => 2,
                'voornaam' => 'Stein',
                'tussenvoegsel' => null,
                'achternaam' => 'Bergkamp',
                'geboortedatum' => '2009-02-02',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 11,
                'gezinid' => 2,
                'voornaam' => 'Judith',
                'tussenvoegsel' => null,
                'achternaam' => 'Bergkamp',
                'geboortedatum' => '2022-02-05',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 12,
                'gezinid' => 3,
                'voornaam' => 'Mazin',
                'tussenvoegsel' => 'van',
                'achternaam' => 'Vliet',
                'geboortedatum' => '1968-08-18',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 13,
                'gezinid' => 3,
                'voornaam' => 'Selma',
                'tussenvoegsel' => 'van de',
                'achternaam' => 'Heuvel',
                'geboortedatum' => '1965-09-04',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 1,
            ],
            [
                'id' => 14,
                'gezinid' => 4,
                'voornaam' => 'Eva',
                'tussenvoegsel' => null,
                'achternaam' => 'Scherder',
                'geboortedatum' => '200-04-07',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 1,
            ],
            [
                'id' => 15,
                'gezinid' => 4,
                'voornaam' => 'Felicia',
                'tussenvoegsel' => null,
                'achternaam' => 'Scherder',
                'geboortedatum' => '2021-11-29',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 16,
                'gezinid' => 4,
                'voornaam' => 'devin',
                'tussenvoegsel' => null,
                'achternaam' => 'Scherder',
                'geboortedatum' => '2024-03-01',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 17,
                'gezinid' => 5,
                'voornaam' => 'Frieda',
                'tussenvoegsel' => 'de',
                'achternaam' => 'Jong',
                'geboortedatum' => '1980-09-01',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 1,
            ],
            [
                'id' => 18,
                'gezinid' => 5,
                'voornaam' => 'Simeon',
                'tussenvoegsel' => 'de',
                'achternaam' => 'Jong',
                'geboortedatum' => '2018-05-23',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 0,
            ],
            [
                'id' => 19,
                'gezinid' => 6,
                'voornaam' => 'Hanna',
                'tussenvoegsel' => 'van der',
                'achternaam' => 'Berg',
                'geboortedatum' => '1999-09-09',
                'typepersoon' => 'klant',
                'isvertegenwoordiger' => 1,
            ],
        ]);
    }
}