<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $faker = Faker::create();

        $data = [
            [
                'categorie_id' => 1,
                'naam' => 'Appels',
                'soort_allergie' => null,
                'barcode' => '1234567890123',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse appels van het seizoen.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 2,
                'naam' => 'Melk',
                'soort_allergie' => 'Lactose',
                'barcode' => '2345678901234',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Halfvolle melk, vers van de boerderij.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 3,
                'naam' => 'Kipfilet',
                'soort_allergie' => null,
                'barcode' => '3456789012345',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Malse kipfilet, ideaal voor een gezonde maaltijd.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 4,
                'naam' => 'Tomaten',
                'soort_allergie' => null,
                'barcode' => '4567890123456',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Rijpe tomaten, perfect voor salades en sauzen.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 5,
                'naam' => 'Bruin brood',
                'soort_allergie' => null,
                'barcode' => '5678901234567',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Vers gebakken bruin brood van de bakker.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 6,
                'naam' => 'Appelsap',
                'soort_allergie' => null,
                'barcode' => '6789012345678',
                'houdbaarheid' => '2024',
                'omschrijving' => '100% puur appelsap zonder toegevoegde suikers.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 7,
                'naam' => 'Aardbeien',
                'soort_allergie' => null,
                'barcode' => '7890123456789',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse Hollandse aardbeien, zoet en sappig.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 8,
                'naam' => 'Chocoladereep',
                'soort_allergie' => 'Cocoa',
                'barcode' => '8901234567890',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Pure chocoladereep met minstens 70% cacao.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 1,
                'naam' => 'Komkommers',
                'soort_allergie' => null,
                'barcode' => '9012345678901',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Knapperige komkommers, heerlijk in salades.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 2,
                'naam' => 'Yoghurt',
                'soort_allergie' => 'Lactose',
                'barcode' => '0123456789012',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse volle yoghurt van biologische melk.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 3,
                'naam' => 'Zalmfilet',
                'soort_allergie' => null,
                'barcode' => '1234567890123',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse zalmfilet, perfect voor op de barbecue.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 4,
                'naam' => 'Aardappelen',
                'soort_allergie' => null,
                'barcode' => '2345678901234',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse Hollandse aardappelen, geschikt voor elke maaltijd.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 5,
                'naam' => 'Wit brood',
                'soort_allergie' => null,
                'barcode' => '3456789012345',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Vers gebakken wit brood, lekker knapperig van buiten en zacht van binnen.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 6,
                'naam' => 'Sinaasappelsap',
                'soort_allergie' => null,
                'barcode' => '4567890123456',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Vers geperst sinaasappelsap, rijk aan vitamine C.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 7,
                'naam' => 'Peren',
                'soort_allergie' => null,
                'barcode' => '5678901234567',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Sappige peren, ideaal als gezond tussendoortje.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 8,
                'naam' => 'Witte chocolade',
                'soort_allergie' => 'Cocoa',
                'barcode' => '6789012345678',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Romige witte chocolade, perfect voor zoetekauwen.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 1,
                'naam' => 'Paprika',
                'soort_allergie' => null,
                'barcode' => '7890123456789',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse rode paprika, ideaal voor diverse gerechten.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 2,
                'naam' => 'Karnemelk',
                'soort_allergie' => 'Lactose',
                'barcode' => '8901234567890',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Traditionele karnemelk, verfrissend en licht zuur van smaak.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 3,
                'naam' => 'Verse pasta',
                'soort_allergie' => null,
                'barcode' => '9012345678901',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Ambachtelijk gemaakte verse pasta, klaar in slechts enkele minuten.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 4,
                'naam' => 'Ui',
                'soort_allergie' => null,
                'barcode' => '0123456789012',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse Hollandse ui, onmisbaar in vele gerechten.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 5,
                'naam' => 'Maisbrood',
                'soort_allergie' => null,
                'barcode' => '1234567890123',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Vers gebakken maisbrood, heerlijk zoet en luchtig van structuur.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 6,
                'naam' => 'Verse sinaasappels',
                'soort_allergie' => null,
                'barcode' => '2345678901234',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Handgeplukte verse sinaasappels, sappig en vol van smaak.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 7,
                'naam' => 'Druiven',
                'soort_allergie' => null,
                'barcode' => '3456789012345',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Zoete druiven, perfect als gezonde snack tussendoor.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 8,
                'naam' => 'Pure chocolade',
                'soort_allergie' => 'Cocoa',
                'barcode' => '4567890123456',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Intens smakende pure chocolade met 85% cacao.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 1,
                'naam' => 'Wortelen',
                'soort_allergie' => null,
                'barcode' => '5678901234567',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse Hollandse wortelen, ideaal voor stoofschotels en salades.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 2,
                'naam' => 'Room',
                'soort_allergie' => 'Lactose',
                'barcode' => '6789012345678',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse room, perfect voor het maken van sauzen en desserts.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 3,
                'naam' => 'Diepvriespizza',
                'soort_allergie' => null,
                'barcode' => '7890123456789',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Italiaanse diepvriespizza, rijkelijk belegd en krokant van bodem.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 4,
                'naam' => 'Peterselie',
                'soort_allergie' => null,
                'barcode' => '8901234567890',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Verse peterselie, ideaal als smaakmaker en garnering.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 5,
                'naam' => 'Stokbrood',
                'soort_allergie' => null,
                'barcode' => '9012345678901',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Vers gebakken stokbrood, knapperig van buiten en zacht van binnen.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 6,
                'naam' => 'Perensap',
                'soort_allergie' => null,
                'barcode' => '0123456789012',
                'houdbaarheid' => '2024',
                'omschrijving' => '100% puur perensap, verfrissend en vol van smaak.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 7,
                'naam' => 'Bananen',
                'soort_allergie' => null,
                'barcode' => '1234567890123',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Rijpe bananen, perfect voor smoothies en als gezonde snack.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categorie_id' => 8,
                'naam' => 'Hazelnoten chocolade',
                'soort_allergie' => 'Cocoa',
                'barcode' => '2345678901234',
                'houdbaarheid' => '2024',
                'omschrijving' => 'Melkchocolade met stukjes hazelnoot, een klassieker onder de chocolades.',
                'status' => 'op voorraad',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('product')->insert($data);
    }
}
